### ISSUE TITLE
Problems with aurelias content projection

### ISSUE THREAD

**Issue by zedL** [arabsight/aurelia-mdl-plugin#4]
Hello,

I use mdl layout elements with aurelias content projection feature.
I use it with multible slot´s to project other content (with mdl elements) in my layout-views.
IE and Edge stop working, Chrome works fine. Looks like the elements does not upgraded any more...

René

It is an mdl-menu (used in a mdl-layout as aurelia custom element) that breaks the thing down.

**Comment by arabsight** [comment]
Hey René, I couldn't reproduce the issue, could you please provide some code or better yet put together a small project that reproduces the issue.
side note: also make sure you're using the latest version, it fixes an issue where some nested elements doesn't upgrade.
Thanks.

**Comment by zedL** [comment]
Ok ok, 

here it is: 
https://github.com/zedL/aurelia-mdl-plugin-upgrade-issue

I placed a mdl-menu in the footer. If you remove the menue the slot content works fine in IE and Edge, otherwise not.

**Comment by arabsight** [comment]
Hey René, and thanks for the link, its fixed, pull the latest version (0.1.15).
