### ISSUE TITLE
Force Update of Slider

### ISSUE THREAD

**Issue by graywolf336** [arabsight/aurelia-mdl-plugin#5]
Is there a way to force the update of a slider? As right now a slider input is bound and it's value changes, however the slider doesn't change.

**Comment by arabsight** [comment]
I'm assuming you're binding to the value property, if so:
> Although the value attribute is used to set a slider's initial value, it should not be used to modify the value programmatically; instead, use the MDL change() method. For example, assuming that slider1 is a slider object and newvalue is a variable containing the desired value, do not use slider1.value = newvalue; instead, use slider1.MaterialSlider.change(newvalue). [Docs](https://getmdl.io/components/#sliders-section)

**Comment by arabsight** [comment]
here's an example using a custom element:
```js
import {
    bindable,
    bindingMode,
    inlineView,
    customElement
} from 'aurelia-framework';

@inlineView(`<template>
    <input class="mdl-slider mdl-js-slider"
        type="range" ref="slider" value.bind="value"
        min="0" max="100" tabindex="0" >
</template>`)
@customElement('mdl-slider')
export class MdlSlider {
    @bindable({
        defaultBindingMode: bindingMode.twoWay
    }) value;

    valueChanged(newValue, oldValue) {
        if (!newValue || !this.slider || (newValue === oldValue)) return;
        this.slider.MaterialSlider.change(newValue);
    }
}
```

```html
<mdl-slider value.bind="progress"></mdl-slider>
```

**Comment by graywolf336** [comment]
Awesome, thank you very much! 👍
