### ISSUE TITLE
Compatibility with MDL 1.3.0

### ISSUE THREAD

**Issue by dinkzilla** [arabsight/aurelia-mdl-plugin#6]
I upgraded to material design lite v 1.3.0 and the javascript components all stopped working. Reverting to 1.2.1 (where I had been previously) fixed it.

**Comment by arabsight** [comment]
Hi @dinkzilla and sorry for the late response, I just tried v1.3.0 with the demo repo: https://github.com/arabsight/aurelia-mdl-plugin-demo and its working fine. I'm using v1.0.0 of the plugin.if you could provide a reproduction of the issue that would be great.
